module.exports = {
  POSTS: 'posts',
  USERS: 'users',
  FIRST_NAME: 'firstName',
  LAST_NAME: 'lastName',
  POSTER_UID: 'posterUID',
  POST_COUNT: 'postCount',
  POST_DESCRIPTION: 'postDescription',
  STARTING_LOCATION: 'startingLocation',
  DESTINATION: 'destination',
  DESTINATION_TIME: 'departureTime',
  RETURN_TIME: 'returnTime',
  DATE: 'date',
  BIO: 'bio',
  PHONE_NUMBER: 'phoneNumber',
  RIDES: 'rides',
  POST_STATUS: 'postStatus',
  MATCHES: 'matches',
  POST_ID: 'postId',
  REQUESTS: 'requests',
  USER_POSTS: 'userPosts',
  INTERESTED_POSTS: 'interestedPosts',
};
